spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    mode: HTML
  mvc:
    static-path-pattern: /assets/**
  # ???????
  datasource:
    url: jdbc:mysql://localhost:3306/dialogue?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 133625
    # ???
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # ????????
      initial-size: 8
      # ?????
      max-active: 16
      # ?????
      min-idle: 1
      # ??????
      max-wait: 60000
      # ????
      connection-error-retry-attempts: 3
  resources:
    static-locations: classpath:/static

# mybatis??
mybatis:
  check-config-location: true
  #  mybatis????????mybatis????????
  config-location: "classpath:mybatis-config.xml"
  #  ??xml??
  mapper-locations: "classpath:com/dby/dialogue/mapper/*Mapper.xml"
  #  ??model???
  type-aliases-package: "com.dby.dialogue.entity.*"

# ????
logging:
  pattern:
    # ??????
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [%thread] %clr(%logger){cyan} : %msg%n"
  level:
    #    trace < debug < info < warn < error < fatal
    # ??????
    root: info
    # ???????
    com.dby.dialogue: warn

server:
  port: 8080
